{% set name = "xclim" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b01f48b5582a735a44d260dc8638f59ffee39b19bd3f0da3f9207da87b8427e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - scipy >=1.2
    - numpy >=1.16
    - numba
    - pandas >=0.23
    - fiona >=1.8
    - rtree >=0.9
    - geojson >=2.5.0
    - shapely >=1.6
    - geopandas >=0.7
    - cftime >=1.0.4
    - netCDF4 >=1.4
    - dask >=2.6
    - bottleneck >=1.3,<1.4
    - xarray >=0.14.1
    - pyproj >=2.5
    - pint >=0.9
    - boltons >=20.1
    - scikit-learn >=0.21.3
    - packaging >=20.0
    - pytest

test:
  imports:
    - xclim
    - xclim.ensembles
    - xclim.subset

about:
  home: http://github.com/Ouranosinc/xclim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Library of derived climate variables, ie climate indicators, based on xarray
  description: |
    xclim is a library of functions computing climate indices. It is based on xarray 
    and can benefit from the parallelization provided by dask. Its objective is to
    make it as simple as possible for users to compute indices from large climate 
    datasets, and for scientists to write new indices with very little boilerplate.
  doc_url: https://xclim.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xclim

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
