{% set name = "xclim" %}
{% set version = "0.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7fd8e0eff0ede6f3cc6df1a989a07f7607c49f22817578d46082465954c24f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - scipy >=1.2
    - numpy >=1.16
    - numba
    - pandas >=0.23
    - cftime >=1.4.1
    - dask >=2.6
    - bottleneck >=1.3.1,<1.4
    - xarray >=0.17
    - pint >=0.10
    - boltons >=20.1
    - scikit-learn >=0.21.3
    - jsonpickle
    - pyyaml
    - click
    - packaging >=20.0

test:
  imports:
    - xclim
    - xclim.ensembles
  requires:
    - netcdf4
    - pooch
    - pytest
    - yamale
    - xdoctest
  source_files:
    - xclim
  commands:
    - pytest xclim -m "not requires_docs"
    - pytest --rootdir xclim/testing/tests/ --xdoctest xclim --ignore=xclim/testing/tests

about:
  home: https://github.com/Ouranosinc/xclim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Library of derived climate variables, ie climate indicators, based on xarray
  description: |
    xclim is a library of functions computing climate indices. It is based on xarray 
    and can benefit from the parallelization provided by dask. Its objective is to
    make it as simple as possible for users to compute indices from large climate 
    datasets, and for scientists to write new indices with very little boilerplate.
  doc_url: https://xclim.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xclim

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
