{% set name = "xclim" %}
{% set version = "0.33.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c909d6b94b2ab44f6f6c822cac13504987b4681c656585a1caf37d1de09c4ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
    - pytest-runner
  run:
    - python >=3.8
    - boltons >=20.1
    - bottleneck >=1.3.1,<1.4
    - cf_xarray
    - cftime >=1.4.1
    - click
    - dask >=2.6
    - jsonpickle
    - numba
    - numpy >=1.16
    - pandas >=0.23
    - pint >=0.10
    - pyyaml
    - scikit-learn >=0.21.3
    - scipy >=1.2
    - statsmodels
    - xarray >=0.17

test:
  imports:
    - xclim
    - xclim.ensembles
  requires:
    - netcdf4
    - pooch
    - pytest
    - yamale
    - xdoctest
  source_files:
    - xclim
  commands:
    - pytest xclim -m "not requires_docs"
    - pytest --rootdir xclim/testing/tests/ --xdoctest xclim --ignore=xclim/testing/tests

about:
  home: https://github.com/Ouranosinc/xclim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Library of derived climate variables, ie climate indicators, based on xarray
  description: |
    xclim is a library of functions computing climate indices. It is based on xarray 
    and can benefit from the parallelization provided by dask. Its objective is to
    make it as simple as possible for users to compute indices from large climate 
    datasets, and for scientists to write new indices with very little boilerplate.
  doc_url: https://xclim.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xclim

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
