{% set name = "xclim" %}
{% set version = "0.10.10b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e7a64161293a764bdaf413fc5b2f6ae846adc7ca1a2ef2d5e50cb7e661ab10f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - scipy >=1.2
    - numpy >=1.15
    - pandas >=0.23
    - cftime >=1.0.3
    - netCDF4 >=1.4
    - dask >=1.2
    - bottleneck >=1.2.1
    - xarray >=0.12.2
    - pyproj >=1.9.5.1
    - pint >=0.8
    - boltons >=18.0
    - pytest

test:
  imports:
    - xclim

about:
  home: http://github.com/Ouranosinc/xclim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Library of derived climate variables, ie climate indicators, based on xarray'
  description: |
    xclim is a library of functions computing climate indices. It is based on xarray 
    and can benefit from the parallelization provided by dask. Its objective is to
    make it as simple as possible for users to compute indices from large climate 
    datasets, and for scientists to write new indices with very little boilerplate.
  doc_url: https://xclim.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xclim

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
