{% set name = "xclim" %}
{% set version = "0.43.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41e83fdfa5ba069f4a444e115b3c8ade218804e5e22cead8aa3c81ba45f43c62

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - flit
    - pip
  run:
    - python
    - boltons >=20.1
    - bottleneck >=1.3.1
    - cf_xarray >=0.6.1
    - cftime >=1.4.1
    - click >=8.1
    - dask >=2.6
    - jsonpickle
    - lmoments3 >=1.0.5
    - numba
    - numpy >=1.16
    - pandas >=0.23,<2.0  # [py==38]
    - pandas >=0.23  # [py>=39]
    - pint >=0.10
    - pyyaml
    - scikit-learn >=0.21.3
    - scipy >=1.2
    - statsmodels
    - xarray >=2022.06.0

test:
  imports:
    - xclim
    - xclim.ensembles
    - xclim.sdba
  requires:
    - h5netcdf
    - filelock
    - netcdf4
    - pip
    - pooch
    - pytest
    - pytest-xdist
    - yamale
    - xdoctest
  source_files:
    - tests
    - xclim
  commands:
    - pip check
    - pytest --numprocesses=auto --dist=loadscope tests -m "not requires_docs"  # [not win]
    - pytest --rootdir=tests --xdoctest xclim  # [not win]

about:
  home: https://github.com/Ouranosinc/xclim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Library of derived climate variables, ie climate indicators, based on xarray
  description: |
    xclim is a library of functions computing climate indices. It is based on xarray 
    and can benefit from the parallelization provided by dask. Its objective is to
    make it as simple as possible for users to compute indices from large climate 
    datasets, and for scientists to write new indices with very little boilerplate.
  doc_url: https://xclim.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xclim

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
