{% set name = "xclim" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a6b52a65f79f016e2aa1dba35119e2a35c509a3fcfa37a2ee89a2a9b4988592

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - scipy >=1.2
    - numpy >=1.15
    - pandas >=0.23
    - fiona >=1.8
    - rtree >=0.8
    - geojson >=2.5.0
    - shapely >=1.6
    - geopandas >=0.4
    - cftime >=1.0.4,<1.0.5
    - netCDF4 >=1.4
    - dask >=1.2
    - bottleneck >=1.3
    - xarray ==0.14.1
    - pyproj >=2.4,<3.0
    - pint >0.8,<0.10
    - boltons >=19.0
    - scikit-learn >=0.21.3
    - pytest

test:
  imports:
    - xclim
    - xclim.atmos
    - xclim.icclim
    - xclim.subset

about:
  home: http://github.com/Ouranosinc/xclim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Library of derived climate variables, ie climate indicators, based on xarray'
  description: |
    xclim is a library of functions computing climate indices. It is based on xarray 
    and can benefit from the parallelization provided by dask. Its objective is to
    make it as simple as possible for users to compute indices from large climate 
    datasets, and for scientists to write new indices with very little boilerplate.
  doc_url: https://xclim.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xclim

extra:
  recipe-maintainers:
    - Zeitsperre
    - huard
