travis:
  secure:
    BINSTAR_TOKEN: zNJO+38QHYrxjwTjncGYQbAZo9pBczJzIYaMTvZvlTV/OsRJMZaxUrWRQALsM+UwqvatV1H4NsiBnoQGvOxk2Ey2W9SE0uKPaSpfgb4Frm5lph9AVJVBxh5gaEk4QDFeWnN1Ta+f48wX4JrfnxRH8cPY4Nm90xZpnD6J7Z+CkzTT/iS1ha+eLHd/PVnq8hMKyh87IlK+RMNb3bEZNqF6Tth61V8nA1NQV9Fi8jOu0EHojCslVfsKaejjF+RBTquzr2tusmD+H0kXvmD8dOjAW7pIJZbdG4MmFZ+4vp4h40sfEYf4pVjr3IAsvIRBHr5QsQ5az+GoePK/VF+OsducJDpBwhgBlB42zblCqoQOKQxCUXgyIRs5lETVKQQWOzQK7pxPKuL/PHjwB1QvPqYmKhnhJFB4Suw57ccGUgSVmGndmoVn1+BrgalJj+B/gI7l1wot63e4JQcZ8kLurMHrrI7y8566qlnGLQvhCltdJ7y5aisK8tDdHutVBWJABHnsRL4A1Es8NLB3GmuZFDGg16gVLVW4UMfhTLXSmaOGFC4Wd3bPBAAmURehqC/5PaEDBVtHkl+o4S4y/fnFL0ozrHIt0jG+y1FbqL6ESDWmjmJ9gITkdjC7KlYdryDqHjah9DuJ9ZYEnoANhs1tl3TxTXWjTrhB/u9Lx2fNBmDUb7U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
